In [1]:
import pickle

In [5]:
pickle_path = "/data/home/chandrakanth/a100_code/feb24_code/GPS-MTM/outputs/mtm_mae/2025-03-03_17-45-53/47_class__predictions_375.pkl"

with open(pickle_path, 'rb') as f:
    predictions = pickle.load(f)

In [6]:
batch_pickle_path = "/data/home/chandrakanth/a100_code/feb24_code/GPS-MTM/outputs/mtm_mae/2025-03-03_17-45-53/47_class__batch_375.pkl"

with open(batch_pickle_path, 'rb') as f:
    batch = pickle.load(f)

In [7]:
attention_pickle_path = "/data/home/chandrakanth/a100_code/feb24_code/GPS-MTM/outputs/mtm_mae/2025-03-03_17-45-53/47_class__attention_masks_375.pkl"

with open(attention_pickle_path, 'rb') as f:
    attention_masks = pickle.load(f)

In [8]:
masks_pickle_path = "/data/home/chandrakanth/a100_code/feb24_code/GPS-MTM/outputs/mtm_mae/2025-03-03_17-45-53/masks_375.pkl"

with open(masks_pickle_path, 'rb') as f:
    masks = pickle.load(f)

In [9]:
masks["states"]

tensor([[0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
      

In [10]:
# whenever masks["states"] is 1, get the prediction from predictions["states"] and ground truth from batch["states"]

predictions_list = []
ground_truth_list = []

for i in range(len(masks["states"])):
    if masks["states"][i] == 1:
        try:
            predictions_list.append(predictions["states"][i])
            ground_truth_list.append(batch["states"][i])
        except:
            print("Error at index", i)

Error at index 129
Error at index 130
Error at index 135
Error at index 136
Error at index 139
Error at index 140
Error at index 142
Error at index 144
Error at index 147
Error at index 149
Error at index 150
Error at index 153
Error at index 157
Error at index 160
Error at index 161
Error at index 163
Error at index 164
Error at index 167
Error at index 173
Error at index 174
Error at index 175
Error at index 180
Error at index 181


In [20]:
predictions["states"].numpy()[10].argmax(1)[:45]

array([30, 24,  5,  5,  1,  4, 12, 12,  4,  6, 13,  6, 12, 30,  6,  6,  6,
       20,  3, 20, 20, 36, 36,  6,  0,  6,  6,  6,  3, 20, 40, 40, 40, 40,
       17, 40, 40, 40, 40, 10, 10, 12, 10, 31, 12])

In [19]:
ground_truth_list[10].numpy().argmax(axis=1)[:45]

array([21,  0, 45, 45,  1,  0, 45, 27,  0, 45, 45,  0,  0, 45, 45, 45,  1,
        0, 45,  0, 27, 45, 45, 45,  0, 21, 45, 45,  1,  0, 45,  0, 21, 45,
       10,  0, 45,  1,  0, 45, 27,  0, 45,  0, 27])

In [19]:
ground_truth_list[10].numpy()[-1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32)

In [21]:
ground_truth_list[0][56]

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])

In [10]:
masks["states"].flatten()

tensor([0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1.,
        1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0.,
        0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0.,
        0., 1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1.,
        1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 1., 1.,
        0., 0., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
        1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 0.,
        1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 1.,
        0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0.,
        1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.], dtype=torch

In [11]:
predictions["states"].shape

torch.Size([128, 221, 47])

In [12]:
ground_truth_list[0].size()

torch.Size([221, 47])

In [13]:
attention_masks.shape

torch.Size([128, 221])

In [14]:
batch_pickle_path

'/data/home/chandrakanth/a100_code/feb24_code/GPS-MTM/outputs/mtm_mae/2025-02-28_13-15-50/47_class__batch_375.pkl'

In [15]:
predictions

{'states': tensor([[[-0.0388, -0.1753,  0.0870,  ...,  0.3928,  0.7942,  0.2551],
          [ 0.3249, -0.2713, -0.2934,  ...,  0.0032,  1.8318,  0.0837],
          [ 0.2902, -0.1441, -0.2932,  ...,  0.0869,  1.8531,  0.0911],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],
 
         [[ 0.0234, -0.3020,  0.0371,  ...,  0.2463,  0.7584,  0.2497],
          [ 0.4788, -0.1020, -0.3530,  ...,  0.1182,  1.9905, -0.0650],
          [ 0.3328, -0.0799, -0.2669,  ..., -0.0574,  1.9191, -0.0743],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],
 
         [[ 0.0693, -0.2230, -0.0164,  ...,  0.2036,  0.7986,  0.2461],
          [ 0.2468